version: '3.4'
# name: erezervisi
services:
  erezervisi.sql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: unless-stopped
    # container_name: erezervisi.sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test12345!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - erezervisinet2024

  erezervisi.api:
    restart: unless-stopped
    # container_name: erezervisi.api
    build:
      context: .
      # dockerfile: eRezervisi.Api/Dockerfile
    environment:
      - ConnectionStrings:eRezervisiDb=Server=erezervisi.sql, 1433; Database=IB200054_Dev; User=sa; Password=Test12345!; ConnectRetryCount=0;TrustServerCertificate=True;Trusted_Connection=False;
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5269:5269
    networks:
      - erezervisinet2024
    links:
      - erezervisi.sql
    depends_on:
      - erezervisi.sql
      
networks:
  erezervisinet2024:
    driver: bridge      